sudo: false
language: ruby
gemfile:
- Gemfile
services:
- docker
rvm:
- 2.1
cache: bundler
env:
  matrix:
  - TARGET_CONTAINER_ID=melody
before_script:
- docker build --no-cache -t pattyhama/cent7-jenkins2:1.0 .
- docker images
- docker run -d --name $TARGET_CONTAINER_ID pattyhama/cent7-jenkins2
- docker ps -a
