sudo: false
language: ruby
gemfile:
- Gemfile
services:
- docker
rvm:
- 2.1
cache: bundler
before_install:
- gem update bundler
before_script:
- docker build --no-cache -t melody .
- docker images
- docker run -d --name $TARGET_CONTAINER_ID melody
- docker ps -a
