sudo: false
language: ruby
gemfile:
- Gemfile
services:
- docker
rvm:
- 2.1
cache: bundler
before_script:
- docker build --no-cache -t pattyhama/cent7-jenkins2:1.0 .
- docker run --privileged -d --name $TARGET_CONTAINER_ID pattyhama/cent7-jenkins2:1.0
- docker ps -a
