sudo: false
language: ruby
gemfile:
- Gemfile
services:
- docker
rvm:
- 2.1
cache: bundler
env:
  matrix:
  - TARGET_CONTAINER_ID=melody
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: KrBFkxe+m5ve+DNCNpUcMADquM9kN/s3Yk8wlAl4CoIpNGbwFwfCGtXRteZgQuwVSQWghcw/7K4XjDcDJc54XVXPbozV7seHFCBj/CQnoWzeymYZaftSZaQmQGNsha0BFMiHhtbbA9zJshfSYKQQFtCKkM0+UptClTVe7GTQXET/byzRSJDfObf9Zl0zldSKb2xU2NP/Ovxu/rxMj9pobwaIEPv+h2xf/GMXdQBCImfCzRQc/OiD/Y2T6jAAqtSpyLu0ABRYg0B3ymApnnXVj7RVya1X9wCmQkOJvIjXqgOZXkk4LScC4gTE/PGzWskQgl77g5r7FT8ViURagxd1Z2NT0NoU/sjTziUNOnS796NF2evP3XfnQL5YFKqnWccMpiQtTEcff1z3xAj5vXY1O3g+oKJzQ4H6mxUay6kvuWZLiSBuuTK+Xg1zfjQMa/8a8y8LUE/uBVdsjpEsYk4gmKZSMXcH2g5ms6Nv4l2DUPAuE8F+jK6eLD3Iv3zcWporY55QcC2tUWwybcgh4lzBKEJspsscUFN9YMaXK4A8DOk+hO57bTKPXEk0pJL/DiKyX1EJRH+d5yIz1gkGCIFye/DVzKCvaaRf426bwp3fV6dkbw7t/jSyDXsVET0Fd1l09vF3xfzDlC+pq+4nsP7RLCq9FYZ5v9ae7VEDy6WbhKc=
  - secure: k9mL625M+eVwD+mhVshIOszYoJFjQw10uMpLdALPuk+MAuTldR3bHhpQLQQSn4WiNBxJkBIAjPKDZYn+8KIhEiqHcyObTcTTGdWtY39PgmSHS6XE/oLWhdA960kuWS6Ux7qofgM1xGAopLFzw7TRjkKyePi/YMMD1N/wFJ9aVcEAkB0JkBBpIY+qyoHVlSFYCnz7yCxG4vCcDtiO8CUG1T93dNuWT9CAgIgGVt7TyGUtKcCMpCwPMR1MZcQl9nT8Nv0mUQXJaUkBxmGSkBjvqEcYeWx2htbK7+3zY4QNmst09dfuDR5FxxHe0Dv9iNfG9HtiSXqHihYA4Qs5WYjaALZPPzj0YsXQD7an0QPKO8ALc1s+vLfBl5ZW+59tBpgx8SyAF+dPzGrJSBu3W88BSk+dSmzu4njEaLzLOXoHjUpx6YL2CEQvyjbuhvPhU1kqWEW4MQMK8qy8/alzgCocI/VkKNdLhhEAmdMmATsYd616dQvZgYJemnXESxx72s1aTeseoT3vaw2SZao7q7/l/6pjtrhLqHnPrHJhXyKWERNJlZ6rcp+7uUIMC1JCmpjU2F76yNg0My6qX0gt4ZX9jBacW9JCLHRJPB1Q6Ycjvpx8Fq11eIGvrzzwFtvzmIurkdNfBUNZH9CPVGi5tShQlLWxl9RHcV0EJJ+Y9KfBijU=
  - secure: VnfbS1NKigEM57nsm2ahGThM+8qxrNtBe+2r7SQviqwa8OFV/yfLlAZdcBkAFwc1DZc8dqeRxDDHvG9q/aOLw8pw5ViiCv5F50oJEAHbhkqYKBErpsZKLmCP1+iTpYSlW32EJ5jUrFsHGftNPpan8AgpEehgD+R5bvDNAtZkfqQdGr/aDDjuJhQ1lNHuio/ABeBJ7qecN6LJQCQK4vKRcV7ceTMpfU7g9vUUPGtLXgUi9Hu4dX/PcfcPL7wVndOk9ba4EM/oD5L+4a3BN9to0VA3K4szwGfGk2vbqGv3gTb0evqbjlB5xawsLJX6iuBxd8IBRAyvFu6Qy2hNCFBWaOBh8m8/0OGVW4DDL/+qqM7Wiglbo6Yqb5FOkop4H+BfQj4g/dZrmLT244S6+HB3Txpj6T7WPwrhLpSwPx5Z67lA8sAdyDM5bH0o4pWZi2N1XXr3xfr+EDdB9v7Kn1KMUJJNZE2TwQ6rBBDxWkEQLM5DXiTZpQVlYPwwx/sVtPvEg8n+rO0tqs28TZL0lyPBrCxJftQhcuwyp41pApSjOXOm3EDYd4Sn807HYFmUBBTzQvXPitv1sOgtLHtLfPWlo1VD5iXK31QFEFaelivJvDVuYvT1jECWH3AMqLul46WPLXuo9fMlC8j88OtSF6kvmokyjvfBhzImdoU0N0X69cY=
before_script:
- docker build --no-cache -t melody .
- docker images
- docker run -d --name $TARGET_CONTAINER_ID melody
- docker ps -a
after_success:
- docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
- export REPO=pattyhama/cent7-jenkins2
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
  ; fi`
- docker build -f Dockerfile -t $REPO:$COMMIT .
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO
