sudo: false
language: ruby
gemfile:
- Gemfile
services:
- docker
rvm:
- 2.1
cache: bundler
env:
  matrix:
  - TARGET_CONTAINER_ID=melody
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: 5HXmo8w2iX43wpR5C7/TFZE3blCO8gkors8ptxeSmU5Bj8AmJGgY+njPSmar7QTJesDVov2ctIWi5RHMCBiAyLZ9FOjItwkLmmu7f1PX8KLTN/CjsbxHgaozHJB+FIwkzh3bJ+3kj5KIV99Gmgmg5JIzVxRCntLIzfKlyXOAvpqW0GrkMmQiOcaxomnTZtj3UqdTTHkEZqpFXpfn1hb8B0gKnMLsbc1nc2oj+GwuQoHEJxl19KWdlsa6w6aIzn5pY/Kkf2um6BvU7q0BT+KSU9qUoQTqI+QACB6QWRnc/9Pbff5X/087BA4Vd13Mpg/Rp/aos7Jr2OQWE7fH34aqu4y0Pckj6NBqLa8CLPrkwd+6+kHKw0bFFv0hxgBmx6hJiq6hyMFogsFAzRe+7i3sd5uTyye3ahDyDzfjQkJFaON8csEiCUObhnfXUs5Qk9d6u2Secw35To7aPUC/RDvbhC0vpLopWKLkSHHI9d81sqt5ILheCSQqdaon5rw+8ylt/X291CtS92XQFomvzv2VdehIFxqyA2cKUa9JdpFGwgJfklHXl0YYUlSSK4RWVbw+bm5+0LD5fcrbd2EwOV0Ln1stgwU/bQQq5+1/14gofuXm0ayga5kQqUhBevQ00MXG885/BAQ+8JOc5Tfjyk7mr6LknXQ109VoaQcXhxcOPwY=
  - secure: cvSqlFQv2mGhYk02GRecCQ2oxTzy1oCMsr0N0MfCcCp1Bzlk/Lbfwa5WpycFIeujnzsFQNsGMy0X3qBjUHgo7j5UiWgovGdFjrivf4wMBHxf3S3y9EuztPvlzmNkELFpvC9mEv5YCXYNB8tYBohU5bdG5hIe+dOnG098IOkgednEHou6rmPjbB0YWEapTPP6ziTOuTV5quz6xd8/hMZQQOdsn1LKtchwTJYlAITVr7iCwyNbPbIU5slh8CFUqzB651BKy3jF+FHyj2mA8Exd1pJSNtb85+UjqIg/Qjxa3ad8c7SvWfJxEvhLSdXZgq18b2joBWBSwQ9U0uvmRySnOjMf3b36ZfN4v04rLyq8u1KSvKNzd8D6h2p+Tpd70TBDchtcuonPQd2uvyG2J6z5EGsmdVX/otiRASzawHasMhj5wf5AjblZnQvN9M7FegZqFSL0puzb8gZMoBQ3pA0ghZclu6O1D1/X5lH75PEl/WxuMAmdOl5KCvnFroIesz62OCSlLrKHn6ezyfBwSnaUuNEikgYwV4z9yYo+2vKMwOfgb9HK+/h7tXW5yoGi4HIQmE1GWXsDqiwoCJ4yAwzp4Pcu2YJrEk0qV3XYrTeLCKQPe2YEFxsMO3dc9tKK6dMmc0nvwf9bSWjJcBykQAnt3x6tMbjfGRJUFTxuvws5xx4=
  - secure: zouH6BgmjaqZ+hgwvh6Q7HVmgT0WEQPy0Hf1z4OIeJH4ZRj6jZM7I0eH3CMvynbGBK+wQmatrzE0+oyrnGj0z1eCUjwYkrd0Yqd9TMAUXHyai4M3y0MhN5fhWRwXXD4H/14Bf8OLgMUlGSwOx5hOjEdkcxi2PgLSoeUXWgPpVXjXyw3Sl617JGXIMMMj2KsOe63JFK6Awq5KyPFEJgOWmuLep62osOJP6rmgTRhFDg/AkyAtKwQGE/X0SonTuB9JZHjVuy4rZD/OcF3ylpvQ0wQWi/lZSjzgAaHxVxiD9sgKyHtTYr1TVuoXFyYhPRG9ysbjThZSJXBLL1kJ0NfVpdU5UzH9QZBolbPJi/GxWE7Cavrzp75AO9gi1p6VuPN1jjoz5JGQR+jHCvA2WLh8Ckmjsj8H7blpRWqV4+qZWNmHnGVFmJ1Yl/Ce2fc2016QWHwE+lA5cq7X14lpmA5Nap/zbNjMgJWR0IZMlyg18D90WFw+i3zY9Z0AR/g+DeJijDh2Pmf3H+Lpan9Qtu/Wbz26WKmq5NFFLyy72kWM27AKXmk/JDQcOZU1bj8vzJ6IAo7dJXO2pN69GxYx+JbDyvUqFYSE5xwJYrDu1bGAIdJgu4GELcYdLzBr1mDuN0ij1zJvCkn2Io84fFkgGc9bp8FJlG39OV/BiSgVp6PMAFQ=
  - COMMIT=${TRAVIS_COMMIT::8}
before_script:
- docker build --no-cache -t melody .
- docker images
- docker run -d --name $TARGET_CONTAINER_ID melody
- docker ps -a
after_success:
- docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
- export REPO=pattyhama/cent7-jenkins2
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
  ; fi`
- docker build -f Dockerfile -t $REPO:$COMMIT .
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO

